
import React from 'react';
import ProjectApp from './projects/bankapp/App';
// Auto-generated by AI Architect | Linked at: 1769661249
export default function App() { return (<div className="App"><ProjectApp /></div>); }
